-- =======================================================
-- FitTrack 體態與體重記錄 - Supabase 資料庫初始化腳本
-- 請在 Supabase 的「SQL Editor」中貼上並點擊「Run」執行
-- =======================================================

-- 1. 建立體重與體態記錄資料表 (weight_records)
CREATE TABLE IF NOT EXISTS public.weight_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weight NUMERIC NOT NULL,
    body_fat NUMERIC,
    record_date TEXT NOT NULL,
    note TEXT,
    tags TEXT,
    photo_url TEXT,
    photo_path TEXT,
    photo_angle TEXT DEFAULT 'front',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. 建立使用者個人身材設定資料表 (user_settings)
CREATE TABLE IF NOT EXISTS public.user_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- 插入預設身材目標
INSERT INTO public.user_settings (key, value)
VALUES 
    ('target_weight', '65.0'),
    ('height_cm', '175.0'),
    ('user_name', '體態記錄')
ON CONFLICT (key) DO NOTHING;

-- 3. 建立儲存體態相片的 Storage Bucket (body-photos)
INSERT INTO storage.buckets (id, name, public)
VALUES ('body-photos', 'body-photos', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- 4. 設定權限 (允許公開讀寫，方便個人手機隨時連線)
ALTER TABLE public.weight_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;

-- 允許任何人使用 anon key 讀寫記錄
CREATE POLICY "Allow all on weight_records" ON public.weight_records
FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow all on user_settings" ON public.user_settings
FOR ALL USING (true) WITH CHECK (true);

-- 允許任何人使用 anon key 上傳與讀取相片
CREATE POLICY "Allow all on body-photos" ON storage.objects
FOR ALL USING (bucket_id = 'body-photos') WITH CHECK (bucket_id = 'body-photos');
